apiVersion: v1
kind: Service
metadata:
  name: moviemania-backend
  namespace: moviemania
spec:
  type: NodePort
  selector:
    app: moviemania-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31100
 
