apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviemania-backend
  labels:
    app: moviemania-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviemania-backend
  template:
    metadata:
      name: moviemania-backend
      labels:
        app: moviemania-backend
    spec:
      containers:
        - name: moviemania-backend
          image: devesh121/moviemania_backend:v4.4
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: backend-sec
                  key: PORT
            - name: JWTSECRET
              valueFrom:
                secretKeyRef:
                  name: backend-sec
                  key: JWTSECRET
            - name: JWT_EXPIRE
              valueFrom:
                secretKeyRef:
                  name: backend-sec
                  key: JWT_EXPIRE
            - name: COOKIE_EXPIRE
              valueFrom:
                secretKeyRef:
                  name: backend-sec
                  key: COOKIE_EXPIRE
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: backend-sec
                  key: mongo-url
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: backend-sec
                  key: FRONTEND_URL
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: backend-sec
                  key: ADMIN_EMAIL
            - name: ADMIN_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-sec
                  key: ADMIN_EMAIL_PASSWORD

      #     volumeMounts:
      #       - mountPath: /app
      #         name: backend-volume
      # volumes:
      #   - name: backend-volume
      #     hostPath:
      #       path: ./backend
