apiVersion: v1
kind: Service
metadata:
  name: moviemania-backend
spec:
  selector:
    app: moviemania-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31100
  type: NodePort
 
