version: "3.9"

services:
  # Server service (using devesh121 local tag)
  server:
    image: devesh121/moviemania_backend:v3
    container_name: backend
    ports:
      - "8080:8080" # Adjust port if needed
    env_file: .env
    environment:
      - PORT=$PORT # From separate source
    networks:
      - moviemania
    depends_on:
      - mongodb

  # Client service
  client:
    image: devesh121/moviemania_frontend:v3
    container_name: frontend
    env_file: ./frontend/.env
    ports:
      - "5173:5173" # Adjust port if needed
    networks:
      - moviemania
    depends_on:
      - server

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27018:27018"
    networks:
      - moviemania
    volumes:
      - ./../mydata:/data/db # Adjust path if needed

# Volumes definition (already defined correctly)
volumes:
  mydata:
networks:
  moviemania:
