version: "3.9"

networks:
  moviemania:

services:
  # Server service (using devesh121 local tag)
  server:
    # build: ./backend
    image: devesh121/moviemania_backend:v4
    container_name: backend
    ports:
      - "8080:8080" # Adjust port if needed
    env_file: .env
    environment:
      - PORT=$PORT # From separate source
    networks:
      - moviemania
    # depends_on:
    #   - mongodb

  # Client service
  client:
    # build: ./frontend
    image: devesh121/moviemania_frontend:v4
    container_name: frontend
    env_file: ./frontend/.env
    ports:
      - "5173:5173" # Adjust port if needed
    networks:
      - moviemania
    depends_on:
      - server

  # Database service : This is optional stage because we are using the mongo Atlas database through connection string.
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27018:27018"
    networks:
      - moviemania
    volumes:
      - ./../mydata:/data/db # Adjust path if needed

# Volumes definition (already defined correctly)
volumes:
  mydata:

