apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: moviemania
spec:
  selector:
    app: moviemania-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 31000
